team_imu/base/urls.py
from django.contrib import admin
from django.urls import path
from base import views

urlpatterns = [
    path("register/",views.register,name="register"), 
    path("login/",views.loginUser,name="login"),
    path("logout/",views.logoutUser,name="logout"),
    path('result/',views.result,name="result"),
    path('board/',views.board,name="board"),
    path('result/detail/<int:id>',views.detail,name="detail"),
    path('result/update/<int:id>',views.update,name="update"),
    path('result/delete/<int:id>',views.delete,name="delete"),
    path('photos/',views.photos,name="photos"),
    path('photos_use/<int:id>',views.photos_use,name="photos_use"),
    path('add_photo/<path:slug>',views.add_photo,name="add_photo"),
    path('delete_photo/<path:slug>',views.delete_photo,name="delete_photo"),
    path('map/',views.maps,name="maps"),
    path('map/image_paths', views.ImagesPaths, name="image_paths"),
    path('map/googlemaps', views.googlemaps.map, name = "googlemaps"),
    path('map/control', views.Control, name="control"),
    #path('chatbot', views.Chatbot),
    #burada url = "/base/"den sonrası için açılmış urls kısmı
    #örneğin /base/board/ için buraya uğrayacak ve views.board'a bakacak.
]

team_imu/team_imu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, re_path
from base import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',include("base.urls")),
    path('',views.index,name="index"),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
#img field veya file field'ların gözükmesi için yaptım.(Burada settings.py'dan mediaurl'i aldım)
#document root olarak da media klasörünün adresini verdim.bu da settings.py'da gözüküyordu.

team_imu/base/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.core.files.images import ImageFile




# Create your models here.
IMAGE_TYPES = (("STANDARD","STANDARD"),("EMERGENT","EMERGENT"))
IMAGE_PROCESS =(("A", "AUTONOMOUS"), ("M", "MANUEL"))
ORIENTATIONS = (("N", "N"),
                ("W", "W"),
                ("E", "E"),
                ("S", "S"),
                ("NE", "NE"),
                ("SE", "SE"),
                ("SW", "SW"),
                ("NW", "NW"))
SHAPES = (("NONE", "NONE"), ("CIRCLE", "CIRCLE"), ("SEMICIRCLE", "SEMICIRCLE"), ("QUARTER_CIRCLE", "QUARTER_CIRCLE"), ("TRIANGE", "TRIANGLE"), ("SQUARE", "SQUARE"), ("RECTANGLE", "RECTANGLE"), ("TRAPEZOID", "TRAPEZOID"),
          ("PENTAGON", "PENTAGON"), ("HEXAGON", "HEXAGON"), ("HEPTAGON", "HEPTAGON"), ("OCTAGON", "OCTAGON"), ("STAR", "STAR"), ("CROSS", "CROSS"))
COLORS = (("WHITE", "WHITE"), ("BLACK", "BLACK"), ("RED", "RED"), ("YELLOW", "YELLOW"), ("GRAY", "GRAY"), ("GREEN", "GREEN"), ("PURPLE", "PURPLE"),
          ("BROWN", "BROWN"), ("BLUE", "BLUE"), ("ORANGE", "ORANGE"))

def images():
        path='/media/media/01.png'
        return path
#buradaki modeller ve demet tanımları verilen parametrelere göre yapılmıştır.
class Teams(models.Model):
    id = models.IntegerField(primary_key=True,verbose_name="Team ID")
    username = models.CharField(max_length=50,verbose_name="Username")
    name = models.CharField(max_length=50,verbose_name="Team Username")
    university = models.CharField(max_length=50,verbose_name="Unıversity Name")
    InAir = models.BooleanField()
    latitude = models.FloatField(verbose_name="Latitude")
    longitude = models.FloatField(verbose_name = "Longitude")
    altitude = models.FloatField(verbose_name = "Altitude")
    heading = models.FloatField(verbose_name = "Heading")
    telemetry_id = models.IntegerField(verbose_name="Telemetry ID")
    telemetry_age_sec = models.FloatField()
    telemetry_time_stamp = models.CharField(max_length=50)
class Telemetry(models.Model):
    latitude = models.FloatField(verbose_name="Latitude")
    longitude = models.FloatField(verbose_name = "Longitude")
    altitude = models.FloatField(verbose_name = "Altitude")
    heading = models.FloatField(verbose_name = "Heading")
class Result(models.Model):
    img_name = models.CharField(max_length=50,verbose_name="IMAGE NAME")
    img_type = models.CharField(max_length=15,choices=IMAGE_TYPES)
    shape = models.CharField(max_length=20,choices=SHAPES)
    shape_color = models.CharField(max_length=15,choices=COLORS)
    latitude = models.FloatField(verbose_name="Latitude")
    longitude = models.FloatField(verbose_name="Longitude")
    orientation = models.CharField(max_length=2,choices=ORIENTATIONS)
    alphanumeric = models.CharField(max_length=2)
    alphanumeric_color = models.CharField(max_length=20,choices=COLORS)
    is_autonom = models.CharField(max_length=50,choices=IMAGE_PROCESS)
    description = models.CharField(max_length=225,blank=True,verbose_name="Açıklama")
    file = models.ImageField(upload_to='result',blank=True)
    
    uploaded_at = models.DateTimeField(auto_now_add=True)
    
    objects = models.Manager()
    

    def getImg(self):
        if  (not self.file):
            return self.file
        return True
    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'
    
        
class PhotoModel(models.Model):
    description = models.CharField(max_length=225,blank=True,verbose_name="Açıklama")
    file = models.ImageField(upload_to='media',blank=True,null=True)
    
    uploaded_at = models.DateTimeField(auto_now_add=True)
    
    objects = models.Manager()
    
    



# Create your models here.

    

team_imu/base/forms.py
from django import forms
from .models import Result, PhotoModel
from PIL import Image
from django.core.files import File

#modellerden form oluşturuldu.
class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20,label="Kullanıcı Adı")
    password = forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=20,label="Parola Onayı",widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if(password and confirm_password and password != confirm_password):
            raise forms.ValidationError(message="Parolalar eşleşmiyor!")

        values = {
            "username":username,
            "password":password,
            "confirm_password":confirm_password,
        }
        return values

class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label ="Parola",widget=forms.PasswordInput)

class ResultForm(forms.ModelForm):
    x = forms.FloatField(widget = forms.HiddenInput())
    y = forms.FloatField(widget = forms.HiddenInput())
    width = forms.FloatField(widget = forms.HiddenInput())
    height = forms.FloatField(widget = forms.HiddenInput())
    class Meta:
        model = Result
        fields =  "__all__" 
        widgets = {
            'file': forms.FileInput(attrs={
                'accept': 'image/*'  # this is not an actual validation! don't rely on that!
            })
        }

    def save(self):
        photo = super(ResultForm,self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        
        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200,200),Image.ANTIALIAS)
        resized_image.save(photo.file.path)
        return photo

class PhotoForm(forms.ModelForm):
    img=forms.ImageField()
    class Meta:
        model = PhotoModel
        fields = "__all__"
        verbose_name = 'photo'
        verbose_name_plural = 'photos'


    

team_imu/templates/add_photo.html
{%extends "layout.html"%}

{%block body%}
{%load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="POST" enctype="multipart/form-data" id="formUpload">
            <h3>Results : {{slug}}</h3>
            <hr>
            {% csrf_token %} 
            {{form|crispy}}
            <button tpye="submit" class="alert alert-danger">Kaydet</button> 
            <script>
              $(function () {
            
                /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
                $("#id_file").change(function () {
                  if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                      $("#image").attr("src", e.target.result);
                      $("#modalCrop").modal("show");
                    }
                    reader.readAsDataURL(this.files[0]);
                  }
                });
            
                /* SCRIPTS TO HANDLE THE CROPPER BOX */
                var $image = $("#image");
                var cropBoxData;
                var canvasData;
                $("#modalCrop").on("shown.bs.modal", function () {
                  $image.cropper({
                    viewMode: 1,
                    aspectRatio: 1/1,
                    minCropBoxWidth: 200,
                    minCropBoxHeight: 200,
                    ready: function () {
                      $image.cropper("setCanvasData", canvasData);
                      $image.cropper("setCropBoxData", cropBoxData);
                    }
                  });
                }).on("hidden.bs.modal", function () {
                  cropBoxData = $image.cropper("getCropBoxData");
                  canvasData = $image.cropper("getCanvasData");
                  $image.cropper("destroy");
                });
            
                $(".js-zoom-in").click(function () {
                  $image.cropper("zoom", 0.1);
                });
            
                $(".js-zoom-out").click(function () {
                  $image.cropper("zoom", -0.1);
                });
            
                /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
                $(".js-crop-and-upload").click(function () {
                  var cropData = $image.cropper("getData");
                  $("#id_x").val(cropData["x"]);
                  $("#id_y").val(cropData["y"]);
                  $("#id_height").val(cropData["height"]);
                  $("#id_width").val(cropData["width"]);
                  $("#formUpload").submit();
                });
            
              });
            </script>
            
            
            
            
            
            <!-- MODAL TO CROP THE IMAGE -->
            <div class="modal fade" id="modalCrop">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Crop the photo</h4>
                  </div>
                  <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                  </div>
                  <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                      <button type="button" class="btn btn-default js-zoom-in">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                      </button>
                      <button type="button" class="btn btn-default js-zoom-out">
                        <span class="glyphicon glyphicon-zoom-out"></span>
                      </button>
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Çık</button>
                    <button type="button" class="btn btn-primary js-crop-and-upload">Kırp ve Yükle</button>
                  </div>
                </div>
              </div>
            </div>
        </form>

    </div>
</div>

<div id="js">

</div>
{%endblock body%}


 


  

team_imu/templates/board.html
{%extends "layout.html"%}

{%block body%}
<h3>Board Tablosu</h3>
<a href="/base/result/" class="btn btn-danger">Sonuç Ekle</a>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Img Name</th>
        <th scope="col">Img Type</th>
        <th scope="col">Img</th>
        <th scope="col">Shape</th>
        <th scope="col">Shape Color</th>
        <th scope="col">Latitude</th>
        <th scope="col">Longitude</th>
        <th scope="col">Orientation</th>
        <th scope="col">Alphanumeric</th>
        <th scope="col">Alphanumeric Color</th>
        <th scope="col">Otonom</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>

      </tr>
    </thead>
    <tbody>
      {%if results %}
      {%for result in results%}
      <tr>

        <td><a href="/base/result/detail/{{result.id}}">{{result.img_name}}</a></td>
        <td>{{result.img_type}}</td>
        <td>{{result.img}}</td>
        <td>{{result.shape}}</td>
        <td>{{result.shape_color}}</td>
        <td>{{result.latitude}}</td>
        <td>{{result.longitude}}</td>
        <td>{{result.orientation}}</td>
        <td>{{result.alphanumeric}}</td>
        <td>{{result.alphanumeric_color}}</td>
        <td>{{result.is_autonom}}</td>
        <td><a href="/base/result/update/{{result.id}}" class="btn btn-danger">Update</a></td>
        <td><a href="/base/result/delete/{{result.id}}" class="btn btn-danger">Delete</a></td>


      </tr>
      {%endfor%}
    </tbody>
  </table>
  {%else%}
  <div class="danger alert-danger">
      Sonuç Yok.
  </div>
  {%endif%}

{%endblock body%}

team_imu/templates/control.html
<form id="contactForm2" name="form" action="" method="post">
    {% csrf_token %} 
    <!-- Form input fields here (do not forget your name attributes). -->
    <input type="text" id="control_input2"  onkeydown="myFunction_for_input(event)">
    
</form>




<script type="text/javascript">


function myFunction_for_input(event)
{
    value = event.key;    
    
    //var form = document.getElementById("contactForm1");
    
    //window.alert(data);
    var frm = $('#contactForm2');
    
    frm.submit(function (e) {
        var data = event.key;
        //window.alert(data);
        e.preventDefault();
    
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: {
                'control_input': value,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
         
        });
    });
    
  

  $("form").submit(function () {
    if ($(this).valid()) {
        $(this).submit(function () {
            return false;
        });
        return true;
    }
    else {
        return false;
    }
});

    frm.submit();
    $("#contactForm2").closest('form').find("input[type=text], textarea").val("");
  
    
    //window.alert(data);
    //form.appendChild(event.key);
    

    
    //form.submit(control_input2);
  
    
}
</script>

team_imu/templates/detail.html
{%extends "layout.html"%}
{%block body%}
<h3>Sonuç:{{result.img_name}}</h3>
<hr>
<p>{{result.img_type}}</p>
<hr>
<p>{{result.shape}}</p>
<hr>
<p>{{result.shape}}</p>
<hr>
<p>{{result.shape_color}}</p>
<hr>
<p>{{result.latitude}}</p>
<hr>
<p>{{result.longitude}}</p>
<hr>
<p>{{result.orientation}}</p>
<hr>
<p>{{result.alphanumeric}}</p>
<hr>
<p>{{result.alphanumeric_color}}</p>
<hr>
<p>{{result.is_autonom}}</p>
<hr>
<img class="img-fluid rounded" src="{{result.file.url}}">
{%endblock body%}

team_imu/templates/index.html
{%extends "layout.html"%}
{%load static%}
{%block body3%}
  

<input type="file" name="inputfile"
id="inputfile">
<br>

<pre id="output"></pre>

<script type="text/javascript">
function test()
{


document.getElementById('inputfile').addEventListener('change', function() {
  
var fr=new FileReader();
fr.onload=function(){
    document.getElementById('output')
            .textContent=fr.result;
}
  
fr.readAsText(this.files[0]);
console.log(this.files[0]["name"])
})
}


</script>

<script>
  setTimeout(function(){
  test();
  //window.alert("asds")
},1000)
</script>


<script>
  
  var coordinatesJsonType = {
  "type": "geojson",
  "data": {
    "features": [
  
      {
        "type": "Feature",
        "properties": {
          "level": 1,
          "name": "Bird Exhibit",
          "height": 2,
          "base_height": 0,
          "color": "red"
        },
        "geometry": {
          "coordinates": [
            [
            ]
          ],
          "type": "Polygon"
        }
     
      }
    ],
    "type": "FeatureCollection"
  }
  }
  coordinatesJsonType["data"]["features"][0]["properties"]["height"] = 10;
  //window.alert(coordinatesJsonType["data"]["features"][0]["properties"]["height"]);
/*
var obj = {a: 25, b: 50, c: 75};
var A = Object.create(obj);
var B = Object.create(obj);

var coordinatesJson =  JSON.parse(JSON.stringify(coordinatesJsonType)) 
coordinatesJson["data"]["features"][0]["geometry"]["coordinates"][0].push([5,5])

alert(coordinatesJson["data"]["features"][0]["geometry"]["coordinates"]);

alert(coordinatesJsonType["data"]["features"][0]["geometry"]["coordinates"]);
A.a = 30;
B.a = 40;

//alert(obj.a + " " + A.a + " " + B.a); // 25 30 40

  coordinatesJsonType["data"]["features"][0]["geometry"]["coordinates"][0].push([5,5]);
  coordinatesJsonType["data"]["features"][0]["geometry"]["coordinates"][0].push([10,10]);
  coordinatesJsonType["data"]["features"][0]["geometry"]["coordinates"][0].push([5,5]);
  console.log(coordinatesJsonType);

  var deneme = String(coordinatesJsonType);
  deneme = JSON.parse(deneme);
  */
  const set1 = new Set();

  var selam = {x: 10, y: 20};



  set1.add(selam);
  
  console.log(set1);
  set1.delete(selam);
  // Delete any point with `x > 10`.
  set1.forEach((point) => {
    if (point.x > 10) {
      set1.delete(point);
      window.alert("asdas")
    }
  });

console.log("silindi", set1);
// expected output: 1


</script>


<p>Click the button to demonstrate the prompt box.</p>

<button onclick="myFunction()">Try it</button>

<p id="demo"></p>

<script>
  function myFunction() {
  var value = prompt("Please enter the height of building", "0");

  if (value != null && String(parseInt(value, 10)) != "NaN") {

      value = parseInt(value, 10);
      document.getElementById("demo").innerHTML =
      "Hello " + String(value) + "! How are you today?";
  }

  else
  {
    window.alert("Please enter an integer or float and re-upload your json file!");
  }
}
</script>






<script type="text/javascript" type="text/javascript">
  // Connecting to ROS
  // -----------------
  setTimeout(function(){
    var ros = new ROSLIB.Ros({
    url : 'ws://localhost:9090'
  });

  ros.on('connection', function() {
    console.log('Connected to websocket server.');
  });

  ros.on('error', function(error) {
    console.log('Error connecting to websocket server: ', error);
  });

  ros.on('close', function() {
    console.log('Connection to websocket server closed.');
  });

  var cmdVel = new ROSLIB.Topic({
    ros : ros,
    name : '/cmd_vel',
    messageType : 'geometry_msgs/Twist'
  });

  var twist = new ROSLIB.Message({
    linear : {
      x : 0.1,
      y : 0.2,
      z : 0.3
    },
    angular : {
      x : -0.1,
      y : -0.2,
      z : -0.3
    }
  });
  cmdVel.publish(twist);

  // Subscribing to a Topic
  // ----------------------

  var listener = new ROSLIB.Topic({
    ros : ros,
    name : '/listener',
    messageType : 'std_msgs/String'
  });

  listener.subscribe(function(message) {
    console.log('Received message on ' + listener.name + ': ' + message.data);
  });

  // Calling a service
  // -----------------

  var addTwoIntsClient = new ROSLIB.Service({
    ros : ros,
    name : '/add_two_ints',
    serviceType : 'rospy_tutorials/AddTwoInts'
  });

  var request = new ROSLIB.ServiceRequest({
    a : 1,
    b : 2
  });

  addTwoIntsClient.callService(request, function(result) {
    console.log('Result for service call on '
      + addTwoIntsClient.name
      + ': '
      + result.sum);
  });

  // Getting and setting a param value
  // ---------------------------------

  ros.getParams(function(params) {
    console.log(params);
  });

  var maxVelX = new ROSLIB.Param({
    ros : ros,
    name : 'max_vel_y'
  });

  maxVelX.set(0.8);
  maxVelX.get(function(value) {
    console.log('MAX VAL: ' + value);
  });

  },5000);
</script>
</head>

<body>
  <h1>Simple roslib Example</h1>
  <p>Check your Web Console for output.</p>
</body>

  
{%endblock body3%}

team_imu/templates/login.html
{%extends "layout.html"%}

{%block body%}
{%load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="POST">
            <h3>Giriş Yap</h3>
            <hr>
            {% csrf_token %} 
            {{form|crispy}}
            <button tpye="submit" class="alert alert-danger">Giriş Yap</button> 
        </form>

    </div>
</div>


{%endblock body%}

team_imu/templates/photo_list.html
{% extends 'layout.html' %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}
  <h1 class="page-header">Album</h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
    {{selam}}
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <div class="row" style="margin-top: 20px">
    {% for photo in photos %}
      <div class="col-sm-4 col-md-3">
        <img src="{{ photo.file.url }}" class="thumbnail">
      </div>
    {% endfor %}
  </div>

{% endblock %}

team_imu/templates/register.html
{%extends "layout.html"%}

{%block body%}
{%load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="POST">
            <h3>Kayıt Ol</h3>
            <hr>
            {% csrf_token %} 
            {{form|crispy}}
            <button tpye="submit" class="alert alert-danger">Giriş Yap</button> 
        </form>

    </div>
</div>
    
{%endblock body%}

team_imu/templates/result.html
{%extends "layout.html"%}

{%block body%}
{%load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="POST" enctype="multipart/form-data" id="formUpload">
            <h3>Results {{result_photo.file.url}}</h3>
            <hr>
            {% csrf_token %} 
            {{form|crispy}}
            <button tpye="submit" class="alert alert-danger">Kaydet</button> 
            <script>
              $(function () {
            
                /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
                $("#id_file").change(function () {
                  if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                      $("#image").attr("src", e.target.result);
                      $("#modalCrop").modal("show");
                    }
                    reader.readAsDataURL(this.files[0]);
                  }
                });
            
                /* SCRIPTS TO HANDLE THE CROPPER BOX */
                var $image = $("#image");
                var cropBoxData;
                var canvasData;
                $("#modalCrop").on("shown.bs.modal", function () {
                  $image.cropper({
                    viewMode: 1,
                    aspectRatio: 1/1,
                    minCropBoxWidth: 200,
                    minCropBoxHeight: 200,
                    ready: function () {
                      $image.cropper("setCanvasData", canvasData);
                      $image.cropper("setCropBoxData", cropBoxData);
                    }
                  });
                }).on("hidden.bs.modal", function () {
                  cropBoxData = $image.cropper("getCropBoxData");
                  canvasData = $image.cropper("getCanvasData");
                  $image.cropper("destroy");
                });
            
                $(".js-zoom-in").click(function () {
                  $image.cropper("zoom", 0.1);
                });
            
                $(".js-zoom-out").click(function () {
                  $image.cropper("zoom", -0.1);
                });
            
                /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
                $(".js-crop-and-upload").click(function () {
                  var cropData = $image.cropper("getData");
                  $("#id_x").val(cropData["x"]);
                  $("#id_y").val(cropData["y"]);
                  $("#id_height").val(cropData["height"]);
                  $("#id_width").val(cropData["width"]);
                  $("#formUpload").submit();
                });
            
              });
            </script>
            
            
            
            
            
            <!-- MODAL TO CROP THE IMAGE -->
            <div class="modal fade" id="modalCrop">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Crop the photo</h4>
                  </div>
                  <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                  </div>
                  <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                      <button type="button" class="btn btn-default js-zoom-in">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                      </button>
                      <button type="button" class="btn btn-default js-zoom-out">
                        <span class="glyphicon glyphicon-zoom-out"></span>
                      </button>
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Çık</button>
                    <button type="button" class="btn btn-primary js-crop-and-upload">Kırp ve Yükle</button>
                  </div>
                </div>
              </div>
            </div>
        </form>

    </div>
</div>


{%endblock body%}
<div id="js">

</div>

 


  

team_imu/templates/update.html
{%extends "layout.html"%}

{%block body%}
{%load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="POST" enctype="multipart/form-data">
            <h3>Güncelle</h3>
            <hr>
            {% csrf_token %} 
            {{form|crispy}}
            <button tpye="submit" class="alert alert-danger">Kaydet</button> 
        </form>

    </div>
</div>
{%endblock body%}